# Data Analytics Platform Consolidation - Node Profile
# Deal LOST - Closed January 2026

node_id: "DATA_ANALYTICS"
realm_id: "ACME"
name: "Data Analytics Platform Consolidation"
purpose: "Consolidate fragmented analytics tools onto unified data analytics platform"

# Node lifecycle
status: "cancelled"  # planning | active | on_hold | completed | cancelled
operating_mode: "pre_sales"  # pre_sales | implementation | post_sales | renewal
created: "2025-09-10"
closed_date: "2026-01-10"
close_reason: "lost_to_competitor"
target_completion: "2026-06-30"

# Blueprint classification
blueprint:
  archetype: competitive_displacement
  domain: data_analytics
  track: standard
  reference_blueprint: A02_competitive

# Commercial
commercial:
  opportunity_arr: 420000
  probability: 0
  final_probability: 0
  peak_probability: 65
  stage: "closed_lost"
  loss_reason: "Champion departure, new CDO selected Databricks"
  loss_category: "stakeholder_change"
  competitor_won: "Databricks"

# Node-specific stakeholders
stakeholders:
  primary_contacts:
    - name: "Thomas Richter"
      title: "VP Data & Analytics"
      department: "Data Engineering"
      influence: "high"
      relationship: "champion"
      decision_role: "technical_buyer"
      status: "left_company"
      departure_date: "2025-11-28"

    - name: "Anna Bergmann"
      title: "Chief Data Officer"
      department: "Executive"
      influence: "critical"
      relationship: "blocker"
      decision_role: "economic_buyer"
      status: "new_appointment"
      start_date: "2025-12-01"
      notes: "Replaced Thomas Richter's reporting line, brought Databricks preference"

    - name: "Dr. Sarah Chen"
      title: "Head of Engineering"
      department: "Platform Engineering"
      influence: "medium"
      relationship: "supporter"
      decision_role: "technical_influencer"

# Enabled playbooks (from Blueprint)
enabled_playbooks:
  strategic:
    - "PB_001"  # Three Horizons
    - "PB_201"  # SWOT
    - "PB_301"  # Value Engineering
    - "PB_401"  # Customer Health Score
  operational:
    - "OP_RSK_001"  # Register Risk
    - "OP_ACT_001"  # Create Action
    - "OP_ESC_001"  # Escalate
    - "OP_MTG_001"  # Process Meeting

# Node-specific thresholds
thresholds:
  minimum_arr: 300000
  health_score_warning: 60
  health_score_critical: 40
  escalation_days: 5

# Initiative details (at close)
initiative:
  id: "INIT_003"
  name: "Analytics Platform Evaluation"
  phase: "closed_lost"
  start_date: "2025-09-15"
  close_date: "2026-01-10"
  evaluation_criteria:
    - "Unified dashboard across all data sources"
    - "Self-service analytics for business users"
    - "Real-time data pipeline processing"
    - "Cost reduction vs. current tooling"

# Competitive landscape
competitive:
  incumbents:
    - vendor: "Tableau"
      product: "Tableau Server"
      contract_end: "2026-03-31"
      annual_spend: 180000
      pain_points:
        - "Limited real-time capability"
        - "High per-seat licensing"
        - "No data engineering features"

    - vendor: "Microsoft"
      product: "Power BI Premium"
      contract_end: "2026-06-30"
      annual_spend: 95000
      relationship: "moderate"

  winner:
    - vendor: "Databricks"
      product: "Databricks Lakehouse Platform"
      threat_level: "critical"
      notes: "New CDO Anna Bergmann had prior Databricks relationship from previous role"

  threats:
    - vendor: "Snowflake"
      product: "Snowflake Data Cloud"
      threat_level: "low"
      notes: "Evaluated briefly, dismissed on cost"

# Relationships to other nodes
relationships:
  depends_on: []
  related_to:
    - node_id: "SECURITY_CONSOLIDATION"
      relationship: "same_realm"
      notes: "Security node was tracking analytics data pipeline requirements"
  parent_node: null

# Loss analysis
loss_analysis:
  primary_cause: "Champion departure (Thomas Richter left ACME)"
  secondary_causes:
    - "New CDO brought incumbent vendor preference (Databricks)"
    - "POC results were strong but not decisive enough to overcome relationship bias"
    - "Budget was reallocated before final decision"
    - "Compressed decision timeline after leadership change"
  preventable: "Partially - multi-threading beyond single champion would have helped"
  lessons_learned:
    - "Never rely on a single champion for deal progression"
    - "Build executive-level relationships beyond the primary contact"
    - "When leadership changes occur, accelerate stakeholder engagement"
    - "POC excellence alone cannot overcome strong incumbent relationships"

last_updated: "2026-01-12"
updated_by: "sa_agent"
