# Security Platform Consolidation - Node Profile
# Autonomous initiative within ACME realm

node_id: "SECURITY_CONSOLIDATION"
realm_id: "ACME"
name: "Security Platform Consolidation"
purpose: "Consolidate 12 security tools onto unified Security solution"

# Node lifecycle
status: "active"  # planning | active | on_hold | completed | cancelled
operating_mode: "pre_sales"  # pre_sales | implementation | post_sales | renewal
created: "2026-01-01"
target_completion: "2026-12-31"

# Blueprint classification
blueprint:
  archetype: competitive_displacement
  domain: security
  track: premium
  reference_blueprint: A02_competitive

# Commercial
commercial:
  opportunity_arr: 800000
  probability: 60
  stage: "discovery"
  next_milestone: "POC approval"
  next_milestone_date: "2026-02-01"

# Node-specific stakeholders
stakeholders:
  primary_contacts:
    - name: "Klaus Hoffman"
      title: "CISO"
      department: "Information Security"
      influence: "high"
      relationship: "evaluator"
      decision_role: "economic_buyer"

    - name: "Dr. Sarah Chen"
      title: "Head of Engineering"
      department: "Platform Engineering"
      influence: "high"
      relationship: "champion"
      decision_role: "technical_buyer"

# Enabled playbooks (from Blueprint)
enabled_playbooks:
  strategic:
    - "PB_001"  # Three Horizons
    - "PB_201"  # SWOT
    - "PB_301"  # Value Engineering
    - "PB_401"  # Customer Health Score
    - "PB_701"  # Five Forces
  operational:
    - "OP_RSK_001"  # Register Risk
    - "OP_ACT_001"  # Create Action
    - "OP_ESC_001"  # Escalate
    - "OP_MTG_001"  # Process Meeting
    - "OP_HLT_001"  # Health Alert

# Node-specific thresholds
thresholds:
  minimum_arr: 500000
  health_score_warning: 60
  health_score_critical: 40
  escalation_days: 3

# Current initiative details
initiative:
  id: "INIT_002"
  name: "Security POC"
  phase: "poc"
  start_date: "2026-01-15"
  target_date: "2026-03-15"
  poc_success_criteria:
    - "Detect 95% of known threat patterns"
    - "Ingest from 5 log sources"
    - "Sub-second query response"
    - "Demonstrate SIEM consolidation value"

# Competitive landscape
competitive:
  incumbents:
    - vendor: "LegacySIEM"
      product: "LegacySIEM Enterprise Security"
      contract_end: "2026-09-30"
      annual_spend: 450000
      pain_points:
        - "High cost per GB"
        - "Complex licensing"
        - "Limited cloud capabilities"

    - vendor: "SecurityVendorA"
      product: "Falcon"
      contract_end: "2027-03-31"
      relationship: "strong"

  threats:
    - vendor: "Microsoft"
      product: "Sentinel"
      threat_level: "medium"
      notes: "Bundled with M365 E5"

# Relationships to other nodes
relationships:
  depends_on: []
  related_to:
    - node_id: "OBSERVABILITY_ROLLOUT"
      relationship: "data_sharing"
      notes: "Security will consume APM data for threat correlation"
  parent_node: null

last_updated: "2026-01-14"
updated_by: "sa_agent"
