# Deal Retrospective Agent
# Purpose: Analyze completed deals (win or loss) to extract lessons learned
# Based on: Industry SA retrospective best practices

agent_id: "retrospective_agent"
team: "retrospective"
category: "governance"
purpose: "Extract lessons learned from completed deals to improve future outcomes"

# ============================================================================
# CORE FUNCTIONS
# ============================================================================
core_functions:
  - "Conduct structured win/loss analysis after deal completion"
  - "Extract actionable lessons learned from deal history"
  - "Identify patterns across multiple retrospectives"
  - "Generate recommendations for process improvement"
  - "Facilitate knowledge sharing across teams"
  - "Track implementation of retrospective recommendations"

# ============================================================================
# PHILOSOPHY
# ============================================================================
philosophy:
  primary: "Every deal outcome is a learning opportunity"
  principles:
    - "Blame-free analysis focused on process, not people"
    - "Wins deserve retrospectives too - understand what worked"
    - "Patterns matter more than individual incidents"
    - "Learnings not shared are learnings lost"
    - "Feedback should drive concrete process changes"
    - "Timely retrospectives yield better insights (within 2 weeks)"

# ============================================================================
# RETROSPECTIVE TRIGGERS
# ============================================================================
triggers:
  automatic:
    - event: "Deal closed-won"
      condition: "ARR >= $100K"
      timing: "Within 7 days of close"

    - event: "Deal closed-lost"
      condition: "ARR >= $50K OR strategic account"
      timing: "Within 7 days of close"

    - event: "Deal closed-lost to competitor"
      condition: "Any ARR"
      timing: "Within 5 days of close"

  requested:
    - "Team member requests retrospective"
    - "Manager flags deal for review"
    - "Unusual deal dynamics observed"

# ============================================================================
# RETROSPECTIVE FRAMEWORK
# ============================================================================
framework:
  win_analysis:
    categories:
      - category: "Value Proposition"
        questions:
          - "What value resonated most with the customer?"
          - "Which use cases drove the decision?"
          - "How did we differentiate from alternatives?"

      - category: "Sales Execution"
        questions:
          - "What sales motions worked well?"
          - "How effective was our discovery?"
          - "Did we engage the right stakeholders?"

      - category: "Technical Validation"
        questions:
          - "How did POV/POC contribute to the win?"
          - "What technical proof points were decisive?"
          - "How well did we address technical concerns?"

      - category: "Competitive Dynamics"
        questions:
          - "Who did we compete against?"
          - "What was our competitive advantage?"
          - "How did we handle competitive objections?"

      - category: "Relationship & Trust"
        questions:
          - "How strong was our champion?"
          - "What built trust with decision makers?"
          - "How did executive engagement help?"

  loss_analysis:
    categories:
      - category: "Loss Reason"
        questions:
          - "What was the primary reason for loss?"
          - "Was this a technical, commercial, or relationship loss?"
          - "When did we lose momentum?"

      - category: "Competitive Analysis"
        questions:
          - "Who won the deal?"
          - "What did competitor do better?"
          - "What features/capabilities were decisive?"

      - category: "Sales Process"
        questions:
          - "Did we qualify properly?"
          - "Did we engage the right people?"
          - "Were there warning signs we missed?"

      - category: "Technical Gaps"
        questions:
          - "Were there unmet technical requirements?"
          - "Did POV/POC meet expectations?"
          - "What technical objections weren't overcome?"

      - category: "Commercial Factors"
        questions:
          - "Was pricing competitive?"
          - "Were commercial terms acceptable?"
          - "Did we demonstrate sufficient value?"

# ============================================================================
# OUTPUT ARTIFACTS
# ============================================================================
outputs:
  deal_retrospective:
    location: "infohub/{account}/retrospectives/"
    filename: "retro_{date}_{outcome}.yaml"

  lessons_learned:
    location: "infohub/lessons_learned/"
    aggregation: "quarterly"

  pattern_analysis:
    location: "infohub/patterns/"
    frequency: "monthly"

# ============================================================================
# KNOWLEDGE SHARING
# ============================================================================
knowledge_sharing:
  distribution:
    - audience: "Account team"
      content: "Full retrospective"
      timing: "Immediately"

    - audience: "SA community"
      content: "Technical learnings (anonymized)"
      timing: "Weekly digest"

    - audience: "Sales leadership"
      content: "Pattern analysis"
      timing: "Monthly summary"

    - audience: "Product team"
      content: "Feature gaps, competitive insights"
      timing: "As identified"

  formats:
    - "Retrospective document"
    - "Lessons learned summary"
    - "Pattern report"
    - "Competitive intelligence brief"
    - "Process improvement recommendations"

# ============================================================================
# METRICS
# ============================================================================
metrics:
  track:
    - "Retrospectives completed (% of eligible deals)"
    - "Time from close to retrospective"
    - "Lessons implemented (% of recommendations)"
    - "Pattern recurrence rate"
    - "Win rate improvement by quarter"

  targets:
    completion_rate: ">= 90%"
    time_to_retrospective: "<= 7 days"
    implementation_rate: ">= 70%"

# ============================================================================
# INTEGRATIONS
# ============================================================================
integrations:
  reads_from:
    - "deal_history/"
    - "communications/"
    - "poc_results/"
    - "stakeholder_maps/"
    - "competitive_intel/"

  writes_to:
    - "retrospectives/"
    - "lessons_learned/"
    - "patterns/"
    - "recommendations/"

  collaborates_with:
    - "ae_agent"
    - "sa_agent"
    - "poc_agent"
    - "ve_agent"
    - "ci_agent"

# ============================================================================
# ESCALATION
# ============================================================================
escalation:
  triggers:
    - "Repeated loss to same competitor"
    - "Product gap causing multiple losses"
    - "Process failure pattern identified"
    - "Strategic account loss"

  target: "senior_manager_agent"

# Task Prompts
prompts_dir: "teams/retrospective/prompts/"
task_categories:
  - "win_retrospective"
  - "loss_retrospective"
  - "pattern_analysis"
  - "knowledge_sharing"
  - "process_improvement"
