# Enterprise Search Platform Evaluation - Node Profile

node_id: "SEARCH_EVALUATION"
realm_id: "INITECH"
name: "Enterprise Search Platform Evaluation"
purpose: "Win enterprise search deal for Initech SaaS platform"

status: "active"
operating_mode: "pre_sales"
created: "2026-01-18"
target_completion: "2026-02-28"

# Blueprint classification
blueprint:
  archetype: technical_evaluation
  domain: search
  track: poc
  reference_blueprint: A02_comparative

commercial:
  opportunity_arr: 150000
  probability: 50
  stage: "technical_evaluation"
  next_milestone: "POC kickoff"
  next_milestone_date: "2026-01-27"

stakeholders:
  primary_contacts:
    - name: "Bill Lumbergh"
      title: "VP Technology"
      influence: "high"
      relationship: "developing"
      decision_role: "economic_buyer"

    - name: "Peter Gibbons"
      title: "Platform Engineering Lead"
      influence: "high"
      relationship: "champion"
      decision_role: "technical_buyer"

    - name: "Samir Nagheenanajar"
      title: "Senior Developer"
      influence: "medium"
      relationship: "advocate"
      decision_role: "evaluator"

competitive:
  threats:
    - vendor: "Algolia"
      threat_level: "high"
      notes: "Strong ease-of-use perception, but expensive at scale"

    - vendor: "OpenSearch (build)"
      threat_level: "low"
      notes: "Customer prefers buy over build"

  our_differentiation:
    - "TCO at scale ($120K vs Algolia $220K projected)"
    - "Vector/semantic search built-in (Algolia lacks)"
    - "Open APIs, no vendor lock-in"

  poc_success_criteria:
    - "Ingest 10K docs in < 5 minutes"
    - "P95 query response < 100ms"
    - "User relevance satisfaction > 4/5"
    - "100% multi-tenant data isolation"
    - "Time to first search < 4 hours"

last_updated: "2026-01-20"
updated_by: "system"
