# Observability Platform Renewal - Node Profile

node_id: "OBSERVABILITY_RENEWAL"
realm_id: "GLOBEX"
name: "Observability Platform Renewal"
purpose: "Retain and recover at-risk observability account facing churn"

status: "active"
operating_mode: "renewal"
created: "2026-01-12"
target_completion: "2026-04-30"

# Blueprint classification
blueprint:
  archetype: retention_renewal
  domain: observability
  track: premium
  reference_blueprint: A02_champion_rebuild

commercial:
  opportunity_arr: 180000
  probability: 30
  stage: "at_risk"
  next_milestone: "Recovery plan execution"
  next_milestone_date: "2026-02-15"

stakeholders:
  primary_contacts:
    - name: "Robert Martinez"
      title: "VP Operations"
      influence: "high"
      relationship: "detractor"
      decision_role: "economic_buyer"

    - name: "Emily Watson"
      title: "IT Director"
      influence: "medium"
      relationship: "potential_ally"
      decision_role: "technical_buyer"

competitive:
  threats:
    - vendor: "ObservabilityVendorA"
      threat_level: "critical"
      notes: "Active evaluation, demo scheduled, developers already using free tier"

  risk_factors:
    - "Champion (Michael Torres) departed November 2025"
    - "Usage declined 30% quarter over quarter"
    - "Support satisfaction critically low"
    - "CFO questioning spend"

last_updated: "2026-01-14"
updated_by: "system"
